name: "Chromatic"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Isso é necessário para que o Chromatic tenha o histórico completo do git
          fetch-depth: 0
      - name: Instalar dependências
        run: npm install
        # Ou yarn install, se você usa yarn
      - name: Publicar Storybook no Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
